default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 6000
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASS") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'vovosinha_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'vovosinha_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'vovosinha_production' } %>
